prometheus:
  prometheusSpec: # elastic-search serviceMonitor scrape configuration
    logLevel: debug
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector:
      matchNames:
        - monitoring
grafana: # disables grafana installation
  enabled: false
